(() => {
'use strict';
const E=Evolution,C=EvolutionContent,S=EvolutionStorage,$=id=>document.getElementById(id);
const loaded=S.load();let game=loaded.game,s=game.worlds[game.active];
const scene=new EvolutionArt.Scene($('world')),sound=new EvolutionSound(),modal=$('modal');
let selected=null,drag=null,manualPause=false,otherTab=false,last=0,uiClock=0,saveClock=0,gamepadClock=0,hiddenAt=0,toastClock=0;
const sessionId=String(Date.now())+'-'+Math.random().toString(36).slice(2),ownerKey=S.key+'-owner';
let storageAvailable=true;try{localStorage.setItem(ownerKey,sessionId);}catch{storageAvailable=false;}
let startupReward=E.offline(game),lastMilestone=null;
const route=location.pathname.split('/').pop();
const routeBiome=C.biomes.findIndex(b=>b.file===route||route==='library-'+b.file);
if(routeBiome>0&&routeBiome<=game.unlocked)game.active=routeBiome;
s=game.worlds[game.active];
const fmt=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}),compact=new Intl.NumberFormat('pt-BR',{notation:'compact',maximumFractionDigits:1});
const number=n=>n>=100000?compact.format(n):fmt.format(n);
const paused=()=>manualPause||otherTab||modal.open||document.hidden;
function persist(checkpoint=false){if(otherTab)return;game.savedAt=Date.now();storageAvailable=S.save(game,checkpoint);$('saveStatus').textContent=storageAvailable?'SALVO NESTE DISPOSITIVO':'SAVE INDISPONÍVEL · EXPORTE NAS OPÇÕES';}
function announce(text){$('announcer').textContent=text;}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');toastClock=3.5;announce(text);}
function configure(){scene.configure(game.settings);sound.configure(game.settings,game.active);document.body.classList.toggle('reduce-motion',!scene.motion);}
function select(c){selected=c;scene.selected=c;const b=C.biomes[game.active];$('selectedInfo').textContent=c?`${b.names[c.level-1]} · nível ${c.level} · +${number(2**(c.level-1)*(1+s.upgrades[0]*.35)*(game.active===2?1.25:1)*(1+game.cycles*.25))}/s`:'Escolha uma forma para conhecê-la.';$('recycle').disabled=!c;if(c)announce(`${b.names[c.level-1]}, nível ${c.level}.`);}
function clearDrag(){drag=null;scene.pointer=null;}
function switchWorld(i){if(i<0||i>game.unlocked)return;persist(true);game.active=i;s=game.worlds[i];select(null);clearDrag();scene.enter(i);configure();history.replaceState(null,'',C.biomes[i].file);update();persist();}
function open(title,html,eyebrow='AMOEBA EVOLUTION'){clearDrag();$('modalTitle').textContent=title;$('modalContent').innerHTML=html;$('modalEyebrow').textContent=eyebrow;if(!modal.open)modal.showModal();sound.pause(true);}
function close(){modal.close();}
$('closeModal').onclick=close;
modal.addEventListener('close',()=>{sound.pause(paused());last=0;});
function update(){
 const b=C.biomes[game.active],target=s.best>=b.unlock?20:b.unlock;
 document.documentElement.style.setProperty('--accent',b.color);$('chapterLabel').textContent=`${String(game.active+1).padStart(2,'0')} / ${b.name.toUpperCase()}`;$('habitatTitle').textContent=b.title;$('subtitle').textContent=b.tagline;
 $('fieldLabel').textContent=`${b.name.toUpperCase()} / ${game.active<4?'CULTURA VIVA':'EXPEDIÇÃO CÓSMICA'}`;
 $('objectiveTitle').textContent=game.active===7?(game.completed?'O ciclo está completo.':'Uma nova origem.'):(game.unlocked>game.active?`${C.biomes[game.active+1].name} está aberto.`:`${C.biomes[game.active+1].name} espera.`);
 $('objective').textContent=s.best>=b.unlock?'Continue descobrindo as 20 formas ou siga sua jornada.':`Descubra ${b.names[b.unlock-1]}, a forma de nível ${b.unlock}, ${game.active===7?'para completar esta jornada.':'para abrir a próxima etapa.'}`;
 $('best').textContent=`Nível ${s.best} / ${target}`;$('discovered').textContent=`${s.discovered.length}/20 descobertas`;$('objectiveProgress').style.width=`${s.best/target*100}%`;
 $('nextWorld').hidden=!(game.unlocked>game.active||game.completed);$('nextWorld').textContent=game.active===7?'Celebrar a jornada':`Explorar ${C.biomes[game.active+1]?.name||''}`;
 $('ruleTitle').textContent=b.rule;$('ruleDescription').textContent=b.perk;
 [...$('habitats').children].forEach((button,i)=>{button.disabled=i>game.unlocked;button.classList.toggle('active',i===game.active);button.setAttribute('aria-current',i===game.active?'page':'false');button.title=i>game.unlocked?`Alcance o nível ${C.biomes[i-1].unlock} em ${C.biomes[i-1].name}`:C.biomes[i].perk;button.innerHTML=`<span>${String(i+1).padStart(2,'0')} ${i>game.unlocked?'· BLOQUEADO':''}</span>${C.biomes[i].name}`;});
 [...$('upgradeList').children].forEach((button,i)=>{const u=C.upgrades[i];button.innerHTML=`<b>${s.upgrades[i]>=u.max?'MÁX.':number(E.upgradePrice(s,i))}</b><strong>${u.name}</strong><small>${i===2?`Cultivo no nível ${E.startLevel(s,game.active)}`:u.desc} · ${s.upgrades[i]}/${u.max}</small>`;});
 const m=E.mission(s,game.active);$('missionIndex').textContent=`${Math.min(5,s.mission+1)}/5`;$('missionTitle').textContent=m?.title||'Habitat estudado.';$('missionDescription').textContent=m?`${m.desc} (${m.current}/${m.target})`:'Todas as tarefas concluídas. As descobertas continuam.';$('claim').hidden=!m;if(m){$('claim').disabled=!m.ready;$('claim').textContent=m.ready?'Receber recompensa':'Em andamento';$('claim').classList.toggle('ready',m.ready);}
 $('hint').textContent=s.merges===0?'Arraste uma criatura sobre outra igual. Ou toque nas duas.':s.merges<4?'Encontros em sequência rendem mais energia. Experimente um combo.':s.charge===100?'Pulso pronto! Combine vários pares com um toque.':'Toque em duas formas iguais ou arraste para combinar.';
 refreshNumbers();
}
function refreshNumbers(){
 $('coins').textContent=number(s.coins);$('income').textContent=`+${number(E.income(s,game.active,game.cycles))} / segundo`;$('count').textContent=`${s.creatures.length} / ${C.capacity}`;
 $('buy').textContent=`+ Cultivar Nv.${E.startLevel(s,game.active)} · ${number(E.price(s,game.active))}`;$('buy').disabled=paused()||s.coins<E.price(s,game.active)||s.creatures.length>=C.capacity;
 $('pulse').textContent=s.charge>=100?'Pulso pronto':`Pulso · ${Math.floor(s.charge)}%`;$('pulse').disabled=paused()||s.charge<100||!E.pair(s);$('pulse').classList.toggle('charged',s.charge>=100);$('pulse').title=`Combina até ${game.active===7?5:3} pares. Cada fusão manual carrega o pulso.`;
 const progress=Math.min(100,s.spawn/E.interval(s,game.active)*100);$('spawnProgress').style.width=`${progress}%`;$('spawnBar').setAttribute('aria-valuenow',String(Math.floor(progress)));$('spawnText').textContent=s.creatures.length>=C.capacity?'Habitat cheio · combine ou devolva formas':`Uma nova vida em ${Math.max(0,Math.ceil(E.interval(s,game.active)-s.spawn))}s`;
 $('combo').hidden=s.combo<2||s.comboLeft<=0;$('comboValue').textContent=`${s.combo} encontros · +${(s.combo-1)*10}%`;$('comboProgress').style.width=`${s.comboLeft/(game.active===1?8:5)*100}%`;
 [...$('upgradeList').children].forEach((b,i)=>b.disabled=paused()||s.upgrades[i]>=C.upgrades[i].max||s.coins<E.upgradePrice(s,i));
 $('pauseCover').hidden=!manualPause&&!otherTab;$('pause').textContent=manualPause?'Continuar':'Pausar';
}
C.biomes.forEach((b,i)=>{const button=document.createElement('button');button.onclick=()=>switchWorld(i);$('habitats').append(button);});
C.upgrades.forEach((u,i)=>{const button=document.createElement('button');button.className='upgrade';button.onclick=()=>{if(paused()||!E.buyUpgrade(s,i))return;sound.play('buy',i+2);update();persist(true);medals();};$('upgradeList').append(button);});
function buy(){if(paused())return;const c=E.add(s,game.active,true);if(!c)return;scene.birth(c);sound.play('buy',c.level);update();persist();}
$('buy').onclick=buy;
function resultFeedback(result){scene.burst(result.creature,number(result.reward),result.discovery);sound.play(result.discovery?'discover':'merge',result.creature.level);if(result.discovery)toast(`${C.biomes[game.active].names[result.creature.level-1]} · nova forma, nível ${result.creature.level}`);}
function afterMerge(){const milestone=E.unlock(game);update();persist(true);medals();if(milestone!==null)showMilestone(milestone);}
function fuse(a,b){if(paused())return false;const result=E.merge(s,a,b,game.active);if(!result)return false;select(result.creature);resultFeedback(result);afterMerge();return true;}
function pulse(){if(paused())return;const results=E.pulse(s,game.active);if(!results.length){toast('Carregue o pulso com fusões e mantenha um par no habitat.');return;}results.forEach(resultFeedback);select(results[results.length-1].creature);sound.play('pulse',6);afterMerge();}
$('pulse').onclick=pulse;
$('claim').onclick=()=>{const reward=E.claim(s,game.active);if(!reward)return;toast(`Missão concluída · +${number(reward)} energia`);sound.play('discover',4);update();persist(true);medals();};
$('recycle').onclick=()=>{if(!selected||paused())return;const c=selected;s.creatures=s.creatures.filter(v=>v!==c);const reward=4*2**(c.level-1);s.coins=Math.min(1e12,s.coins+reward);scene.burst(c,number(reward));select(null);toast('Forma devolvida à natureza. Sua descoberta continua na coleção.');update();persist(true);};
function togglePause(){manualPause=!manualPause;clearDrag();sound.pause(paused());last=0;refreshNumbers();if(manualPause)persist();}
$('pause').onclick=togglePause;
$('resume').onclick=()=>{if(otherTab){const current=S.load();game=current.game;s=game.worlds[game.active];otherTab=false;try{localStorage.setItem(ownerKey,sessionId);}catch{}scene.enter(game.active);configure();select(null);update();}manualPause=false;sound.unlock();sound.pause(paused());last=0;refreshNumbers();};
const canvas=$('world');
function coords(e){const rect=canvas.getBoundingClientRect();return{x:(e.clientX-rect.left)/rect.width,y:(e.clientY-rect.top)/rect.height};}
function hit(p){return [...s.creatures].reverse().find(c=>Math.hypot((c.x-p.x)*scene.width,(c.y-p.y)*scene.height)<scene.radius()+12);}
canvas.onpointerdown=e=>{if(paused()||drag)return;sound.unlock();const p=coords(e),c=hit(p);if(!c){select(null);return;}const previous=selected;select(c);drag={id:e.pointerId,c,start:p,previous,moved:false,offset:{x:c.x-p.x,y:c.y-p.y}};canvas.setPointerCapture(e.pointerId);canvas.focus({preventScroll:true});};
canvas.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;const p=coords(e);if(Math.hypot((p.x-drag.start.x)*scene.width,(p.y-drag.start.y)*scene.height)>6)drag.moved=true;if(drag.moved){scene.pointer=drag.c;drag.c.x=E.clamp(p.x+drag.offset.x,.09,.91);drag.c.y=E.clamp(p.y+drag.offset.y,.16,.82);}};
canvas.onpointerup=e=>{if(!drag||drag.id!==e.pointerId)return;const d=drag;clearDrag();if(d.moved){const target=s.creatures.filter(c=>c!==d.c&&c.level===d.c.level).sort((a,b)=>Math.hypot(a.x-d.c.x,a.y-d.c.y)-Math.hypot(b.x-d.c.x,b.y-d.c.y)).find(c=>Math.hypot((c.x-d.c.x)*scene.width,(c.y-d.c.y)*scene.height)<scene.radius()*2.2);if(target)fuse(d.c,target);else persist();}else if(d.previous&&d.previous!==d.c&&s.creatures.includes(d.previous)&&d.previous.level===d.c.level)fuse(d.previous,d.c);};
canvas.onpointercancel=()=>{clearDrag();};canvas.onlostpointercapture=()=>clearDrag();canvas.oncontextmenu=e=>e.preventDefault();
function selectNext(direction){if(!s.creatures.length)return;const index=s.creatures.indexOf(selected);select(s.creatures[(index+direction+s.creatures.length)%s.creatures.length]);}
function mergeSelected(){selected ||= s.creatures[0];const b=s.creatures.find(c=>c!==selected&&c.level===selected?.level&&c.level<20);if(b)fuse(selected,b);else toast(selected?.level===20?'Esta forma atingiu o nível máximo.':'Ainda não há um par para esta forma.');}
canvas.onkeydown=e=>{if(paused())return;const keys=['ArrowRight','ArrowLeft','ArrowUp','ArrowDown','Enter',' ','c','C','p','P'];if(keys.includes(e.key))e.preventDefault();if(['ArrowRight','ArrowDown'].includes(e.key))selectNext(1);if(['ArrowLeft','ArrowUp'].includes(e.key))selectNext(-1);if(e.key==='Enter'||e.key===' ')mergeSelected();if(e.key.toLowerCase()==='c')buy();if(e.key.toLowerCase()==='p')pulse();};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.open&&!otherTab){e.preventDefault();togglePause();}});
const thumbnailCache=new Map();function thumb(b,l){const key=b+':'+l;if(!thumbnailCache.has(key))thumbnailCache.set(key,scene.thumbnail(b,l));return thumbnailCache.get(key);}
function showMilestone(which){lastMilestone=which;if(which==='complete'){ending();return;}const b=C.biomes[which];open(`Você chegou a ${b.name}.`,`<div class="discovery-art"><img src="${thumb(which,Math.min(8,which+2))}" alt="Uma forma de ${b.name}"></div><p class="story">${b.lore}</p><div class="perk-card"><strong>${b.rule}</strong><p>${b.perk}</p></div><button class="primary wide" id="exploreNow">Explorar ${b.name}</button><button class="quiet wide" id="stayHere">Continuar neste habitat</button>`,'UM NOVO HORIZONTE');$('exploreNow').onclick=()=>{close();switchWorld(which);};$('stayHere').onclick=close;}
$('nextWorld').onclick=()=>game.active===7?ending():switchWorld(game.active+1);
function ending(){open('Tudo começou com uma gota.',`<div class="discovery-art"><img src="${thumb(7,12)}" alt="Nova origem"></div><p class="story">Você levou a vida da primeira célula até além das estrelas. Cada encontro deixou uma marca. Agora, o universo tem uma nova história para contar.</p><div class="ending-stats"><div><b>${number(game.worlds.reduce((n,w)=>n+w.merges,0))}</b><span>encontros</span></div><div><b>${game.worlds.reduce((n,w)=>n+w.discovered.length,0)}</b><span>descobertas</span></div><div><b>8</b><span>mundos</span></div></div><p>Continue buscando as 160 formas ou comece um novo ciclo com +25% de produção permanente. Sua coleção e suas conquistas ficam guardadas.</p><button class="primary wide" id="rebirth">Começar ciclo ${game.cycles+2}</button><button class="quiet wide" id="keepExploring">Continuar explorando</button>`,'JORNADA CONCLUÍDA');$('keepExploring').onclick=close;$('rebirth').onclick=()=>{open('Uma nova primeira vez.','<p>Os habitats, a energia e as melhorias serão reiniciados. Sua coleção e conquistas continuam guardadas, e a produção ganha +25%. Uma cópia do progresso anterior fica nas opções.</p><button class="primary wide" id="confirmRebirth">Recomeçar com o bônus</button>','NOVO CICLO');$('confirmRebirth').onclick=()=>{persist(true);if(E.rebirth(game)){s=game.worlds[0];close();switchWorld(0);toast(`Ciclo ${game.cycles+1} · +${game.cycles*25}% de produção`);}};};}
function collection(){const b=C.biomes[game.active],seen=new Set([...s.discovered,...game.archive[game.active]]);open('Caderno de descobertas',`<p>${b.name} · ${seen.size} de 20 formas. A arte acompanha as criaturas que você encontra.</p><div class="catalog">${b.names.map((name,i)=>seen.has(i+1)?`<button class="specimen" data-level="${i+1}"><img src="${thumb(game.active,i+1)}" alt="${name}"><small>${String(i+1).padStart(2,'0')}</small><strong>${name}</strong></button>`:`<div class="specimen locked"><b>?</b><small>FORMA ${String(i+1).padStart(2,'0')}</small></div>`).join('')}</div><p class="fine-print">Uma fantasia sobre encontros e transformações. As formas e sua sequência são ficcionais.</p>`,'COLEÇÃO VIVA');$('modalContent').querySelectorAll('[data-level]').forEach(button=>button.onclick=()=>{const l=Number(button.dataset.level);open(b.names[l-1],`<div class="discovery-art"><img src="${thumb(game.active,l)}" alt="${b.names[l-1]}"></div><p class="story">${b.lore}</p><p>Forma ${l} de ${b.name}. ${l===20?'O ponto mais alto desta linhagem.':`Dois encontros desta forma dão origem a ${b.names[l]}.`}</p><button class="wide" id="backCollection">Voltar à coleção</button>`,'FORMA '+String(l).padStart(2,'0'));$('backCollection').onclick=collection;});}
$('collection').onclick=collection;
const medalDefs=[
{id:'first',name:'Um primeiro encontro',desc:'Faça sua primeira fusão.',test:g=>g.worlds.some(w=>w.merges>0)},
{id:'ten',name:'No ritmo da vida',desc:'Alcance um combo de 10 encontros.',test:g=>g.worlds.some(w=>w.maxCombo>=10)},
{id:'ocean',name:'Pés molhados',desc:'Abra o Oceano.',test:g=>g.unlocked>=1},
{id:'sky',name:'Sem olhar para baixo',desc:'Abra o Céu.',test:g=>g.unlocked>=3},
{id:'space',name:'Pálido ponto azul',desc:'Chegue à Órbita.',test:g=>g.unlocked>=4},
{id:'pulse',name:'Efeito dominó',desc:'Use o pulso evolutivo.',test:g=>g.worlds.some(w=>w.pulses>0)},
{id:'hundred',name:'Cem possibilidades',desc:'Faça 100 fusões.',test:g=>g.worlds.reduce((n,w)=>n+w.merges,0)>=100},
{id:'research',name:'Caderno completo',desc:'Conclua as 5 missões de um habitat.',test:g=>g.worlds.some(w=>w.mission>=5)},
{id:'twenty',name:'Uma forma perfeita',desc:'Descubra uma criatura de nível 20.',test:g=>g.worlds.some(w=>w.best>=20)},
{id:'beyond',name:'Da gota ao cosmos',desc:'Conclua a jornada em Além.',test:g=>g.completed},
{id:'rebirth',name:'Outra volta ao sol',desc:'Comece um novo ciclo.',test:g=>g.cycles>0},
{id:'all',name:'Uma vida de descobertas',desc:'Encontre as 160 formas.',test:g=>g.worlds.every((w,i)=>new Set([...w.discovered,...g.archive[i]]).size===20)}
];
function medals(){const found=medalDefs.filter(m=>!game.medals.includes(m.id)&&m.test(game));found.forEach(m=>game.medals.push(m.id));if(found.length){persist();if(!toastClock)toast(`Conquista · ${found[0].name}`);}}
function journey(){medals();open('Da gota ao cosmos.',`<p class="story">Oito mundos. Uma mesma vontade de continuar.</p><div class="journey-grid">${C.biomes.map((b,i)=>`<button class="journey-card ${i===game.active?'current':''}" data-world="${i}" ${i>game.unlocked?'disabled':''}><img src="${thumb(i,Math.min(8,i+2))}" alt=""><span class="eyebrow">ETAPA ${i+1}</span><strong>${b.name}</strong><small>${i>game.unlocked?`Nível ${C.biomes[i-1].unlock} em ${C.biomes[i-1].name}`:`${game.worlds[i].discovered.length}/20 formas · ${game.worlds[i].mission}/5 missões`}</small></button>`).join('')}</div><h3>Pequenas grandes conquistas · ${game.medals.length}/${medalDefs.length}</h3><div class="medals">${medalDefs.map(m=>`<div class="medal ${game.medals.includes(m.id)?'earned':''}"><span>${game.medals.includes(m.id)?'✦':'◇'}</span><div><strong>${m.name}</strong><small>${m.desc}</small></div></div>`).join('')}</div><p class="fine-print">Ciclo ${game.cycles+1} · bônus permanente de produção: +${game.cycles*25}%.</p>`,'MAPA DA JORNADA');$('modalContent').querySelectorAll('[data-world]').forEach(b=>b.onclick=()=>{close();switchWorld(Number(b.dataset.world));});}
$('journey').onclick=journey;
function help(first=false){open(first?'Um universo cabe numa gota.':'Pequenos encontros, grandes mundos.',`<div class="tutorial-art"><img src="${thumb(0,1)}" alt="Centelha"><span>+</span><img src="${thumb(0,1)}" alt="Centelha"><span>→</span><img src="${thumb(0,2)}" alt="Gota"></div><p class="story">Combine formas iguais. Descubra uma nova vida. Vá da primeira célula até as estrelas, no seu ritmo.</p><ol class="instructions"><li><strong>Encontre um par.</strong> Arraste uma forma sobre outra igual, ou toque nas duas em sequência.</li><li><strong>Cuide do seu mundo.</strong> Criaturas geram energia. Cultive mais e melhore o laboratório.</li><li><strong>Siga o ritmo.</strong> Fusões rápidas dão bônus. Dez fusões carregam o pulso que combina vários pares.</li><li><strong>Vá além.</strong> Cumpra as missões e alcance o nível indicado para abrir outro mundo.</li></ol><p class="fine-print">Teclado: Tab até o habitat, setas para selecionar, Enter para combinar, C para cultivar, P para o pulso e Esc para pausar. Controle padrão: direcional seleciona, A combina, X cultiva, Y ativa o pulso e Start pausa. Ao sair, sua cultura acumula 25% da produção por até 2 horas.</p><button class="primary wide" id="startPlaying">${first?'Começar minha jornada':'Voltar ao universo'}</button>`,'BEM-VINDO À VIDA');$('startPlaying').onclick=()=>{game.tutorial=true;sound.unlock();close();persist(true);};}
$('help').onclick=()=>help();
async function exportSave(){persist();if(window.AmoebaNative){try{await window.AmoebaNative.exportSave(JSON.stringify(game,null,2));}catch{toast('A exportação não foi concluída.');}return;}const blob=new Blob([JSON.stringify(game,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='amoeba-evolution-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function options(){open('Uma pausa para respirar.',`<div class="settings"><div class="setting-row"><label for="soundToggle">Efeitos sonoros</label><input type="checkbox" id="soundToggle" ${game.settings.sound?'checked':''}></div><div class="setting-row"><label for="musicToggle">Ambiente musical</label><input type="checkbox" id="musicToggle" ${game.settings.music?'checked':''}></div><div class="setting-row"><label for="volume">Volume</label><input type="range" id="volume" min="0" max="100" value="${game.settings.volume*100}"></div><div class="setting-row"><label for="motionToggle">Animações e movimento</label><input type="checkbox" id="motionToggle" ${game.settings.motion?'checked':''}></div><div class="setting-row"><label for="quality">Qualidade visual</label><select id="quality"><option value="high" ${game.settings.quality==='high'?'selected':''}>Completa</option><option value="low" ${game.settings.quality==='low'?'selected':''}>Econômica</option></select></div><p class="fine-print">A preferência de movimento reduzido do dispositivo tem prioridade. O modo econômico reduz partículas e resolução para poupar bateria.</p><div class="settings-buttons"><button id="exportSave">Exportar progresso</button><button id="importSave">Importar progresso</button><button id="restoreBackup">Restaurar cópia anterior</button><button id="fullscreen">Tela cheia</button></div><input id="saveFile" type="file" accept="application/json,.json" hidden><button id="resetProgress" class="danger">Recomeçar este habitat</button><p class="fine-print">O jogo fica pausado nesta janela. O progresso pertence a este navegador ou aplicativo. Guarde uma exportação antes de mudar de dispositivo.</p></div>`,'OPÇÕES');
 const bind=(id,k)=>$(id).onchange=()=>{game.settings[k]=$(id).checked;configure();sound.unlock();persist();};bind('soundToggle','sound');bind('musicToggle','music');bind('motionToggle','motion');$('volume').oninput=()=>{game.settings.volume=Number($('volume').value)/100;configure();persist();};$('quality').onchange=()=>{game.settings.quality=$('quality').value;configure();persist();};
 $('exportSave').onclick=exportSave;$('importSave').onclick=()=>$('saveFile').click();$('saveFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error();const candidate=E.cleanGame(JSON.parse(await file.text()));confirmReplacement(candidate,'Importar este progresso?','O progresso atual será substituído. Uma cópia anterior fica disponível nas opções.');}catch{toast('Arquivo incompatível. Escolha uma exportação do Amoeba Evolution.');}};
 $('restoreBackup').disabled=!S.read(S.backup);$('restoreBackup').onclick=()=>{try{confirmReplacement(E.cleanGame(JSON.parse(S.read(S.backup))),'Restaurar a cópia anterior?','Você voltará ao último ponto de recuperação salvo.');}catch{toast('Não foi possível ler a cópia anterior.');}};
 $('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Tela cheia não está disponível neste dispositivo.');}};
 $('resetProgress').onclick=()=>{open('Recomeçar este habitat?',`<p>As criaturas, a energia e as melhorias de ${C.biomes[game.active].name} serão reiniciadas. As descobertas ficam no arquivo da coleção. Uma cópia do progresso atual ficará nas opções.</p><button class="danger wide" id="confirmReset">Recomeçar ${C.biomes[game.active].name}</button>`,'RECOMEÇAR');$('confirmReset').onclick=()=>{persist(true);game.archive[game.active]=[...new Set([...game.archive[game.active],...s.discovered])];s=game.worlds[game.active]=E.fresh();select(null);scene.enter(game.active);close();update();persist();};};
}
function confirmReplacement(candidate,title,description){open(title,`<p>${description}</p><p>Ciclo ${candidate.cycles+1} · ${candidate.unlocked+1} habitats abertos.</p><button class="primary wide" id="confirmImport">Substituir progresso</button>`,'RECUPERAÇÃO');$('confirmImport').onclick=()=>{persist(true);game=candidate;game.savedAt=Date.now();s=game.worlds[game.active];select(null);scene.enter(game.active);configure();close();update();persist();toast('Progresso restaurado.');};}
$('settings').onclick=options;
$('credits').onclick=()=>open('Feito de pequenos encontros.','<p class="story">Amoeba Evolution · Da gota ao cosmos</p><p>Um jogo de fusão e descoberta. Arte procedural, efeitos e ambiente sonoro gerados localmente. Nenhuma imagem ou música externa é necessária para jogar.</p><p>Sem anúncios, compras, contas ou telemetria. Seu progresso e suas preferências ficam no dispositivo. Exportações só são criadas quando você solicita.</p><p class="fine-print">Versão 0.3.0 · Português brasileiro. As formas são ficcionais e não representam uma sequência científica de evolução. Os aplicativos empacotados incluem componentes de terceiros com seus próprios avisos de licença.</p>','SOBRE O JOGO');
let padState=[];
function gamepad(dt){gamepadClock+=dt;if(gamepadClock<.12)return;gamepadClock=0;const pad=navigator.getGamepads?.()?.find?.(p=>p);if(!pad)return;const current=pad.buttons.map(b=>b.pressed);const pressed=i=>current[i]&&!padState[i];if(pressed(9)&&!modal.open&&!otherTab)togglePause();if(!paused()){if(pressed(15)||pressed(13))selectNext(1);if(pressed(14)||pressed(12))selectNext(-1);if(pressed(0))mergeSelected();if(pressed(2))buy();if(pressed(3))pulse();}padState=current;}
function frame(time){const dt=last?Math.min(.1,(time-last)/1000):0;last=time;const isPaused=paused();sound.pause(isPaused);gamepad(dt);
 if(!isPaused){const born=E.tick(s,dt,game.active,game.cycles);if(born){scene.birth(born);update();}scene.update(dt,s.creatures,drag?.c);saveClock+=dt;if(saveClock>=5){persist();saveClock=0;}}
 scene.draw(s.creatures,isPaused?0:dt);uiClock+=dt;if(uiClock>=.15){refreshNumbers();uiClock=0;}if(toastClock>0){toastClock-=dt;if(toastClock<=0)$('toast').classList.remove('visible');}requestAnimationFrame(frame);
}
window.addEventListener('storage',e=>{if(e.key===ownerKey&&e.newValue!==sessionId){otherTab=true;clearDrag();sound.pause(true);toast('O jogo foi aberto em outra janela. Continue em apenas uma para proteger seu progresso.');refreshNumbers();}});
document.addEventListener('visibilitychange',()=>{last=0;clearDrag();if(document.hidden){hiddenAt=Date.now();persist();sound.pause(true);}else{if(!otherTab&&hiddenAt){const reward=E.offline(game);if(reward)toast(`Sua cultura continuou viva · +${number(reward)} energia`);hiddenAt=0;persist();}sound.pause(paused());update();}});
window.addEventListener('amoeba-back',()=>{if(modal.open)close();else if(manualPause){persist();window.AmoebaNative?.exit();}else togglePause();});
window.addEventListener('pagehide',()=>persist());
document.addEventListener('pointerdown',()=>sound.unlock(),{once:true});
configure();scene.enter(game.active);update();medals();persist();requestAnimationFrame(frame);
if(!game.tutorial)help(true);else if(route.startsWith('library'))collection();else if(startupReward)toast(`Bem-vindo de volta · +${number(startupReward)} energia acumulada`);
if(loaded.recovered)toast('Seu progresso foi recuperado. Exporte uma cópia nas opções.');
if('serviceWorker'in navigator&&location.protocol!=='file:'&&!['127.0.0.1','localhost'].includes(location.hostname)&&!window.Capacitor)navigator.serviceWorker.register('sw.js').catch(()=>{});
})();


