(() => {
'use strict';
const E=Evolution,C=EvolutionContent,S=EvolutionStorage,I=EvolutionI18n,$=id=>document.getElementById(id),t=(key,args)=>I.t(key,args),b=i=>I.biome(i);
const loaded=S.load();let game=loaded.game,s=game.worlds[game.active];
let home=true,manualPause=false,otherTab=false,selected=null,drag=null,busy=0,pendingEnding=false,last=0,uiClock=0,saveClock=0,toastClock=0,hiddenAt=0;
const scene=new EvolutionArt.Scene($('world')),homeArt=new EvolutionArt.HomeScene($('homeCanvas')),sound=new EvolutionSound(),modal=$('modal');
const ownerKey=S.key+'-owner',sessionId=Date.now()+'-'+Math.random();
let storageAvailable=true;
try{localStorage.setItem(ownerKey,String(sessionId));}catch{storageAvailable=false;}
let startupReward=E.offline(game);
const paused=()=>home||manualPause||otherTab||modal.open||document.hidden;
const blocked=()=>paused()||busy>0;
function number(n,decimals=0){return new Intl.NumberFormat(I.language,{notation:n>=100000?'compact':'standard',maximumFractionDigits:n>=100000?1:decimals}).format(n);}
function persist(checkpoint=false){if(otherTab)return;game.savedAt=Date.now();storageAvailable=S.save(game,checkpoint);$('saveStatus').textContent=t(storageAvailable?'saved':'saveFailed');}
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');$('announcer').textContent=message;toastClock=3.8;}
function staticText(){document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.documentElement.lang=I.language;$('world').setAttribute('aria-label',t('canvasLabel'));$('habitats').setAttribute('aria-label',t('habitatsLabel'));$('spawnBar').setAttribute('aria-label',t('birthLabel'));$('homeLanguage').value=I.language;}
function configure(){I.set(game.settings.language);scene.configure(game.settings);homeArt.configure(game.settings);sound.configure(game.settings,game.active);document.body.classList.toggle('reduce-motion',!scene.motion);staticText();}
function clearDrag(){drag=null;scene.pointer=null;}
function select(c){selected=c;scene.selected=c;$('selectedInfo').textContent=c?t('selected',{name:b(game.active).names[c.level-1],level:c.level}):t('choose');$('recycle').disabled=!c||blocked();$('partner').hidden=!c||c.level>=E.startLevel(s,game.active);if(c){$('partner').textContent=t('partner',{level:c.level,cost:number(E.creaturePrice(c.level))});$('partner').disabled=blocked()||s.coins<E.creaturePrice(c.level)||s.creatures.length>=C.capacity;$('announcer').textContent=$('selectedInfo').textContent;}}
function open(title,html,eyebrow='AMOEBA EVOLUTION'){clearDrag();$('modalTitle').textContent=title;$('modalContent').innerHTML=html;$('modalEyebrow').textContent=eyebrow;if(!modal.open)modal.showModal();sound.pause(true);}
function close(){modal.close();}
$('closeModal').onclick=close;
modal.addEventListener('close',()=>{sound.pause(paused());last=0;});
function updateHome(){$('continueGame').disabled=!game.started;$('saveSummary').textContent=game.started?t('summary',{cycle:game.cycles+1,world:b(game.active).name,level:s.best}):t('noSave');$('homeCheats').textContent=game.cheated?t('cheatFlag'):'';}
function goHome(){if(modal.open)close();clearDrag();home=true;manualPause=false;$('homeScreen').hidden=false;$('gameShell').hidden=true;homeArt.resize();sound.pause(true);updateHome();persist();}
function startPlay(){if(!game.started)return;home=false;manualPause=false;$('homeScreen').hidden=true;$('gameShell').hidden=false;scene.resize();scene.enter(game.active);sound.unlock();sound.pause(false);update();if(startupReward){toast(t('offline',{n:number(startupReward)}));startupReward=0;}persist();}
function newGame(){const create=()=>{persist(true);const settings={...game.settings};game=E.freshGame();game.settings=settings;game.started=true;game.tutorial=true;s=game.worlds[0];startupReward=0;busy=0;pendingEnding=false;select(null);configure();if(modal.open)close();startPlay();showHelp();};if(!game.started){create();return;}open(t('newConfirm'),`<p>${t('newDesc')}</p><button class="primary wide" id="confirmNew">${t('confirmNew')}</button>`);$('confirmNew').onclick=create;}
$('continueGame').onclick=startPlay;$('newGame').onclick=newGame;$('homeButton').onclick=goHome;$('pauseHome').onclick=goHome;
function changeLanguage(value){game.settings.language=value;configure();update();updateHome();persist();}
$('homeLanguage').onchange=e=>changeLanguage(e.target.value);
function switchWorld(i){if(i<0||i>C.biomes.length-1)return;if(i>game.unlocked){if(i===game.unlocked+1)travelDialog(i);return;}persist();game.active=i;s=game.worlds[i];clearDrag();select(null);busy=0;pendingEnding=false;scene.enter(i);configure();try{history.replaceState(null,'',C.biomes[i].file);}catch{}update();persist();}
function update(){
 const bio=b(game.active),next=game.active+1,target=s.best>=bio.unlock?20:bio.unlock;
 document.documentElement.style.setProperty('--accent',bio.color);$('chapterLabel').textContent=`${String(game.active+1).padStart(2,'0')} / ${bio.name.toUpperCase()}`;$('habitatTitle').textContent=bio.title;$('subtitle').textContent=bio.tagline;
 $('fieldLabel').textContent=bio.name.toUpperCase()+' / '+t(game.active<4?'live':'cosmic');
 $('objectiveTitle').textContent=game.active===7?t(game.completed?'finished':'newOrigin'):t(game.unlocked>=next?'worldOpen':'worldWaits',{world:b(next).name});
 $('objective').textContent=game.active===7?t(game.completed?'keepDiscovering':'lastObjective'):game.unlocked>=next?t('keepDiscovering'):t('objective',{name:bio.names[bio.unlock-1],level:bio.unlock,cost:number(E.travelCost(next))});
 $('best').textContent=t('levelTarget',{n:s.best,target});$('discovered').textContent=t('discoveries',{n:s.discovered.length});$('objectiveProgress').style.width=(s.best/target*100)+'%';
 $('nextWorld').hidden=game.active===7&&!game.completed;$('nextWorld').textContent=game.active===7?t('celebrate'):game.unlocked>=next?t('explore',{world:b(next).name}):t('unlockWorld',{world:b(next).name,cost:number(E.travelCost(next))});
 $('ruleTitle').textContent=bio.rule+' · '+t('focus'+s.focus);$('ruleDescription').textContent=bio.perk;
 [...$('habitats').children].forEach((button,i)=>{button.disabled=i>game.unlocked+1;button.classList.toggle('active',i===game.active);button.setAttribute('aria-current',i===game.active?'page':'false');button.innerHTML=`<span>${String(i+1).padStart(2,'0')} ${i>game.unlocked?'· '+t('locked'):''}</span>${b(i).name}`;});
 [...$('upgradeList').children].forEach((button,i)=>{const u=I.upgrade(i);button.innerHTML=`<b>${s.upgrades[i]>=u.max?t('max'):number(E.upgradePrice(s,i))}</b><strong>${u.name}</strong><small>${i===2?t('growLevel',{n:E.startLevel(s,game.active)}):u.desc} · ${s.upgrades[i]}/${u.max}</small>`;});
 const raw=E.mission(s,game.active),m=raw?I.mission(raw,s.mission):null;$('missionIndex').textContent=Math.min(5,s.mission+1)+'/5';$('missionTitle').textContent=m?.title||t('missionDone');$('missionDescription').textContent=m?`${m.desc} (${m.current}/${m.target})`:t('allTasks');$('claim').hidden=!m;if(m){$('claim').disabled=!m.ready||blocked();$('claim').textContent=t(m.ready?'claim':'inProgress');$('claim').classList.toggle('ready',m.ready);}
 $('hint').textContent=t(s.merges===0?'hintFirst':'hint');$('cheatBadge').hidden=!game.cheated;$('saveStatus').textContent=t(storageAvailable?'saved':'saveFailed');select(selected);refreshNumbers();
}
function refreshNumbers(){
 $('coins').textContent=number(s.coins);$('income').textContent=t('rate',{n:number(E.income(s,game.active,game.cycles),1)});$('count').textContent=`${s.creatures.length} / ${C.capacity}`;
 $('buy').textContent=t('buy',{level:E.startLevel(s,game.active),cost:number(E.price(s,game.active))});$('buy').disabled=blocked()||s.coins<E.price(s,game.active)||s.creatures.length>=C.capacity;
 $('pulse').textContent=s.charge>=100?t('pulseReady'):t('pulse',{n:Math.floor(s.charge)});$('pulse').disabled=blocked()||s.charge<100||!E.pair(s);$('pulse').classList.toggle('charged',s.charge>=100);$('pulse').title=t('pulseHelp',{n:game.active===7?5:3});
 const progress=Math.min(100,s.spawn/E.interval(s,game.active)*100);$('spawnProgress').style.width=progress+'%';$('spawnBar').setAttribute('aria-valuenow',Math.floor(progress));$('spawnText').textContent=s.creatures.length>=C.capacity?t('full'):t('spawn',{n:Math.max(0,Math.ceil(E.interval(s,game.active)-s.spawn))});
 $('combo').hidden=s.combo<2||s.comboLeft<=0;$('comboValue').textContent=t('combo',{n:s.combo,bonus:(s.combo-1)*7});$('comboProgress').style.width=s.comboLeft/((game.active===1?8:5)+(s.focus===0?1:0))*100+'%';
 $('surgeLabel').hidden=s.surge<=0;$('surgeLabel').textContent=t('surge',{n:Math.ceil(s.surge)});$('spark').hidden=s.eventClock<50;$('spark').disabled=blocked();$('spark').title=t('bloomHelp');
 [...$('upgradeList').children].forEach((button,i)=>button.disabled=blocked()||s.upgrades[i]>=C.upgrades[i].max||s.coins<E.upgradePrice(s,i));
 $('pauseCover').hidden=!manualPause&&!otherTab;$('pause').textContent=t(manualPause?'resume':'pause');$('recycle').disabled=!selected||blocked();if(selected)$('partner').disabled=blocked()||s.coins<E.creaturePrice(selected.level)||s.creatures.length>=C.capacity;
 const m=E.mission(s,game.active);if(m)$('claim').disabled=!m.ready||blocked();
}
C.biomes.forEach((_,i)=>{const button=document.createElement('button');button.onclick=()=>switchWorld(i);$('habitats').append(button);});
C.upgrades.forEach((_,i)=>{const button=document.createElement('button');button.className='upgrade';button.onclick=()=>{if(blocked()||!E.buyUpgrade(s,i))return;sound.play('buy',i+2);update();persist();medals();};$('upgradeList').append(button);});
function buy(){if(blocked())return;const c=E.add(s,game.active,true);if(c){scene.birth(c);sound.play('buy',c.level);update();persist();}}
$('buy').onclick=buy;
$('partner').onclick=()=>{if(blocked()||!selected)return;const c=E.buyPartner(s,selected,game.active);if(c){scene.birth(c);sound.play('buy');update();persist();}};
function feedback(result){scene.meld(result.sources,result.creature,result.discovery?t('newForm'):'+'+number(result.reward));sound.play(result.discovery?'discover':'merge',result.creature.level);if(result.discovery)toast(t('discovered',{name:b(game.active).names[result.creature.level-1],level:result.creature.level}));}
function afterMerge(){if(E.unlock(game)==='complete')pendingEnding=true;update();persist();medals();}
function fuse(a,c){if(blocked())return false;const result=E.merge(s,a,c,game.active);if(!result)return false;busy=scene.motion?.62:0;select(result.creature);feedback(result);afterMerge();return true;}
function pulse(){if(blocked())return;const results=E.pulse(s,game.active);if(!results.length){toast(t('pulseMissing'));return;}busy=scene.motion?.62:0;const surviving=new Set(s.creatures);results.filter(r=>surviving.has(r.creature)).forEach(feedback);select(results[results.length-1].creature);sound.play('pulse',6);afterMerge();}
$('pulse').onclick=pulse;
$('claim').onclick=()=>{if(blocked())return;const reward=E.claim(s,game.active);if(reward){toast(t('reward',{n:number(reward)}));sound.play('discover',4);update();persist();medals();}};
$('spark').onclick=()=>{if(blocked())return;const reward=E.gather(s);if(reward){scene.burst({x:.7,y:.4},number(reward));toast(t('bloomReward',{n:number(reward)}));sound.play('pulse',5);update();persist();}};
$('recycle').onclick=()=>{if(!selected||blocked())return;const c=selected;s.creatures=s.creatures.filter(v=>v!==c);const reward=Math.max(1,Math.floor(E.creaturePrice(c.level)*.15));s.coins=Math.min(1e12,s.coins+reward);scene.burst(c,number(reward));select(null);toast(t('released'));update();persist();};
function travelDialog(destination){const prev=game.worlds[destination-1],cost=E.travelCost(destination),ready=prev.best>=C.biomes[destination-1].unlock&&prev.coins>=cost;open(t('gateTitle'),`<div class="discovery-art"><img src="${thumb(destination,5)}" alt=""></div><p>${t('gateDesc',{world:b(destination).name,level:C.biomes[destination-1].unlock,previous:b(destination-1).name,cost:number(cost)})}</p><p>${t('gateBalance',{world:b(destination-1).name,n:number(prev.coins)})}</p><button class="primary wide" id="payTravel" ${ready?'':'disabled'}>${t('unlockWorld',{world:b(destination).name,cost:number(cost)})}</button>${ready?'':`<p class="fine-print">${t('gateMissing')}</p>`}`,t('newHorizon'));$('payTravel').onclick=()=>{if(E.buyTravel(game,destination)){persist();close();switchWorld(destination);medals();showArrival(destination);}};}
function showArrival(i){open(t('arrival',{world:b(i).name}),`<div class="discovery-art"><img src="${thumb(i,6)}" alt=""></div><p class="story">${b(i).lore}</p><div class="perk-card"><strong>${b(i).rule}</strong><p>${b(i).perk}</p></div><button class="primary wide" id="arrivalPlay">${t('explore',{world:b(i).name})}</button>`,t('newHorizon'));$('arrivalPlay').onclick=close;}
$('nextWorld').onclick=()=>game.active===7?ending():switchWorld(game.active+1);
$('adaptation').onclick=()=>{open(t('focus'),`<p>${t('focusIntro',{n:number(E.focusCost(s))})}</p><div class="focus-grid">${[0,1,2].map(i=>`<button data-focus="${i}" ${s.focus===i||s.coins<E.focusCost(s)?'disabled':''}><strong>${t('focus'+i)}</strong><p>${t('focusDesc'+i)}</p><small>${s.focus===i?t('active'):t('selectFocus',{n:number(E.focusCost(s))})}</small></button>`).join('')}</div>`);$('modalContent').querySelectorAll('[data-focus]').forEach(button=>button.onclick=()=>{if(E.setFocus(s,Number(button.dataset.focus))){close();update();persist();}});};
function togglePause(){if(home)return;manualPause=!manualPause;clearDrag();sound.pause(paused());last=0;refreshNumbers();if(manualPause)persist();}
$('pause').onclick=togglePause;
$('resume').onclick=()=>{if(otherTab){game=S.load().game;s=game.worlds[game.active];otherTab=false;try{localStorage.setItem(ownerKey,String(sessionId));}catch{}configure();scene.enter(game.active);select(null);update();}manualPause=false;last=0;sound.unlock();sound.pause(paused());refreshNumbers();};
const canvas=$('world');
function coords(e){const rect=canvas.getBoundingClientRect();return{x:(e.clientX-rect.left)/rect.width,y:(e.clientY-rect.top)/rect.height};}
function hit(p){return [...s.creatures].reverse().find(c=>Math.hypot((c.x-p.x)*scene.width,(c.y-p.y)*scene.height)<scene.radius()+12);}
canvas.onpointerdown=e=>{if(blocked()||drag)return;sound.unlock();const p=coords(e),c=hit(p);if(!c){select(null);return;}const previous=selected;select(c);drag={id:e.pointerId,c,start:p,previous,moved:false,offset:{x:c.x-p.x,y:c.y-p.y}};canvas.setPointerCapture(e.pointerId);canvas.focus({preventScroll:true});};
canvas.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;const p=coords(e);if(Math.hypot((p.x-drag.start.x)*scene.width,(p.y-drag.start.y)*scene.height)>6)drag.moved=true;if(drag.moved){scene.pointer=drag.c;drag.c.x=E.clamp(p.x+drag.offset.x,.09,.91);drag.c.y=E.clamp(p.y+drag.offset.y,.16,.82);}};
canvas.onpointerup=e=>{if(!drag||drag.id!==e.pointerId)return;const d=drag;clearDrag();if(d.moved){const target=s.creatures.filter(c=>c!==d.c&&c.level===d.c.level).sort((a,c)=>Math.hypot(a.x-d.c.x,a.y-d.c.y)-Math.hypot(c.x-d.c.x,c.y-d.c.y)).find(c=>Math.hypot((c.x-d.c.x)*scene.width,(c.y-d.c.y)*scene.height)<scene.radius()*2.2);if(target)fuse(d.c,target);else persist();}else if(d.previous&&d.previous!==d.c&&s.creatures.includes(d.previous)&&d.previous.level===d.c.level)fuse(d.previous,d.c);};
canvas.onpointercancel=clearDrag;canvas.onlostpointercapture=clearDrag;canvas.oncontextmenu=e=>e.preventDefault();
function selectNext(direction){if(!s.creatures.length)return;select(s.creatures[(s.creatures.indexOf(selected)+direction+s.creatures.length)%s.creatures.length]);}
function mergeSelected(){selected ||= s.creatures[0];const match=s.creatures.find(c=>c!==selected&&c.level===selected?.level&&c.level<20);if(match)fuse(selected,match);else toast(t(selected?.level===20?'maxLevel':'noPair'));}
canvas.onkeydown=e=>{if(blocked())return;if(['ArrowRight','ArrowLeft','ArrowUp','ArrowDown','Enter',' ','c','C','q','Q'].includes(e.key))e.preventDefault();if(['ArrowRight','ArrowDown'].includes(e.key))selectNext(1);if(['ArrowLeft','ArrowUp'].includes(e.key))selectNext(-1);if(['Enter',' '].includes(e.key))mergeSelected();if(e.key.toLowerCase()==='c')buy();if(e.key.toLowerCase()==='q')pulse();};
const codes=['HESOYAM','VITALIS','ORBITA','EVOLUIR','PULSAR'];let codeBuffer='',codeAt=0;
function runCheat(code){if(!game.started||otherTab||busy>0){toast(t('cheatFail'));return false;}if(!E.cheat(game,code)){toast(t('cheatFail'));return false;}s=game.worlds[game.active];configure();scene.enter(game.active);select(null);update();updateHome();persist();toast(t('cheatSuccess',{code}));return true;}
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.altKey||e.metaKey||e.repeat||/^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName))return;if(e.key==='Escape'&&!modal.open&&!home&&!otherTab){e.preventDefault();togglePause();return;}if(paused()||e.key.length!==1)return;const now=performance.now();if(now-codeAt>2500)codeBuffer='';codeAt=now;codeBuffer=(codeBuffer+e.key.toUpperCase()).slice(-12);const found=codes.find(c=>codeBuffer.endsWith(c));if(found){e.preventDefault();e.stopImmediatePropagation();runCheat(found);codeBuffer='';return;}if(codes.some(c=>c.startsWith(codeBuffer))){e.preventDefault();e.stopImmediatePropagation();}else codeBuffer=codes.some(c=>c.startsWith(e.key.toUpperCase()))?e.key.toUpperCase():'';},true);
const thumbnailCache=new Map();function thumb(i,l){const key=i+':'+l;if(!thumbnailCache.has(key))thumbnailCache.set(key,scene.thumbnail(i,l));return thumbnailCache.get(key);}
function collection(){const bio=b(game.active),seen=new Set([...s.discovered,...game.archive[game.active]]);open(t('codex'),`<p>${t('codexIntro',{world:bio.name,n:seen.size})}</p><div class="catalog">${bio.names.map((name,i)=>seen.has(i+1)?`<button class="specimen" data-level="${i+1}"><img src="${thumb(game.active,i+1)}" alt="${name}"><small>${String(i+1).padStart(2,'0')}</small><strong>${name}</strong></button>`:`<div class="specimen locked"><b>?</b><small>${t('form',{n:String(i+1).padStart(2,'0')})}</small></div>`).join('')}</div><p class="fine-print">${t('fiction')}</p>`);$('modalContent').querySelectorAll('[data-level]').forEach(button=>button.onclick=()=>{const l=Number(button.dataset.level);open(bio.names[l-1],`<div class="discovery-art"><img src="${thumb(game.active,l)}" alt="${bio.names[l-1]}"></div><p class="story">${bio.lore}</p><p>${l===20?t('finalForm'):t('formDetail',{name:bio.names[l-1],next:bio.names[l]})}</p><button class="wide" id="backCollection">${t('backCollection')}</button>`,t('form',{n:l}));$('backCollection').onclick=collection;});}
$('collection').onclick=collection;
const medalDefs=[
{id:'first',name:'Um primeiro encontro',desc:'Faça sua primeira fusão.',test:g=>g.worlds.some(w=>w.merges>0)},
{id:'ten',name:'No ritmo da vida',desc:'Alcance um combo de 10 encontros.',test:g=>g.worlds.some(w=>w.maxCombo>=10)},
{id:'ocean',name:'Pés molhados',desc:'Abra o Oceano.',test:g=>g.unlocked>=1},
{id:'sky',name:'Sem olhar para baixo',desc:'Abra o Céu.',test:g=>g.unlocked>=3},
{id:'space',name:'Pálido ponto azul',desc:'Chegue à Órbita.',test:g=>g.unlocked>=4},
{id:'pulse',name:'Efeito dominó',desc:'Use o pulso evolutivo.',test:g=>g.worlds.some(w=>w.pulses>0)},
{id:'hundred',name:'Cem possibilidades',desc:'Faça 100 fusões.',test:g=>g.worlds.reduce((n,w)=>n+w.merges,0)>=100},
{id:'research',name:'Caderno completo',desc:'Conclua as 5 missões de um habitat.',test:g=>g.worlds.some(w=>w.mission>=5)},
{id:'twenty',name:'Uma forma perfeita',desc:'Descubra uma criatura de nível 20.',test:g=>g.worlds.some(w=>w.best>=20)},
{id:'beyond',name:'Da gota ao cosmos',desc:'Conclua a jornada em Além.',test:g=>g.completed},
{id:'rebirth',name:'Outra volta ao sol',desc:'Comece um novo ciclo.',test:g=>g.cycles>0},
{id:'all',name:'Uma vida de descobertas',desc:'Encontre as 160 formas.',test:g=>g.worlds.every((w,i)=>new Set([...w.discovered,...g.archive[i]]).size===20)}];
function medals(){if(game.cheated)return;const found=medalDefs.filter(m=>!game.medals.includes(m.id)&&m.test(game));found.forEach(m=>game.medals.push(m.id));if(found.length){persist();if(!toastClock)toast(t('medalToast',{name:I.medal(found[0],medalDefs.indexOf(found[0])).name}));}}
function journey(){medals();open(t('mapTitle'),`<div class="journey-grid">${C.biomes.map((_,i)=>`<button class="journey-card ${i===game.active?'current':''}" data-world="${i}" ${i>game.unlocked+1?'disabled':''}><img src="${thumb(i,Math.min(8,i+2))}" alt=""><span class="eyebrow">${t('stage',{n:i+1})}</span><strong>${b(i).name}</strong><small>${i>game.unlocked?t('unlockWorld',{world:b(i).name,cost:number(E.travelCost(i))}):t('mapStats',{n:game.worlds[i].discovered.length,m:game.worlds[i].mission})}</small></button>`).join('')}</div><h3>${t('medals',{n:game.medals.length,total:medalDefs.length})}</h3><div class="medals">${medalDefs.map((m,i)=>{const local=I.medal(m,i);return `<div class="medal ${game.medals.includes(m.id)?'earned':''}"><span>${game.medals.includes(m.id)?'✦':'◇'}</span><div><strong>${local.name}</strong><small>${local.desc}</small></div></div>`;}).join('')}</div><p class="fine-print">${t('cycleInfo',{n:game.cycles+1,bonus:game.cycles*15})}</p>`,t('map'));$('modalContent').querySelectorAll('[data-world]').forEach(button=>button.onclick=()=>{const i=Number(button.dataset.world);if(i>game.unlocked)travelDialog(i);else{close();switchWorld(i);}});}
$('journey').onclick=journey;
function ending(){open(t('endingTitle'),`<div class="discovery-art"><img src="${thumb(7,12)}" alt=""></div><p class="story">${t('endingStory')}</p><div class="ending-stats"><div><b>${number(game.worlds.reduce((n,w)=>n+w.merges,0))}</b><span>${t('encounters')}</span></div><div><b>${game.worlds.reduce((n,w)=>n+w.discovered.length,0)}</b><span>${t('discoveriesWord')}</span></div><div><b>8</b><span>${t('worldsWord')}</span></div></div><p>${t('endingDesc')}</p><button class="primary wide" id="rebirth">${t('rebirth',{n:game.cycles+2})}</button><button class="quiet wide" id="keepPlaying">${t('keepPlaying')}</button>`,t('completed'));$('keepPlaying').onclick=close;$('rebirth').onclick=()=>{open(t('rebirthTitle'),`<p>${t('rebirthDesc')}</p><button class="primary wide" id="confirmRebirth">${t('confirmRebirth')}</button>`);$('confirmRebirth').onclick=()=>{persist(true);if(E.rebirth(game)){s=game.worlds[0];close();switchWorld(0);medals();}};};}
function showHelp(){open(t('helpTitle'),`<div class="tutorial-art"><img src="${thumb(0,1)}" alt=""><span>+</span><img src="${thumb(0,1)}" alt=""><span>→</span><img src="${thumb(0,2)}" alt=""></div><p class="story">${t('helpStory')}</p><ol class="instructions">${[1,2,3,4].map(i=>`<li>${t('help'+i)}</li>`).join('')}</ol><p class="fine-print">${t('controls')}</p><button class="primary wide" id="helpClose">${t('back')}</button>`);$('helpClose').onclick=close;}
$('help').onclick=showHelp;$('homeHelp').onclick=showHelp;
async function exportSave(){persist();const text=JSON.stringify(game,null,2);if(window.AmoebaNative){try{await window.AmoebaNative.exportSave(text);}catch{toast(t('exportFail'));}return;}const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='amoeba-evolution-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function replaceDialog(candidate,title){open(title,`<p>${t('replaceDesc')}</p><p>${t('summary',{cycle:candidate.cycles+1,world:b(candidate.active).name,level:candidate.worlds[candidate.active].best})}</p><button class="primary wide" id="confirmImport">${t('replace')}</button>`);$('confirmImport').onclick=()=>{persist(true);game=candidate;game.savedAt=Date.now();s=game.worlds[game.active];busy=0;pendingEnding=false;select(null);scene.enter(game.active);configure();close();update();updateHome();persist();toast(t('restored'));};}
function options(){open(t('options'),`<div class="settings"><div class="setting-row"><label for="languageSelect">${t('language')}</label><select id="languageSelect"><option value="pt-BR" ${I.language==='pt-BR'?'selected':''}>Português</option><option value="en" ${I.language==='en'?'selected':''}>English</option></select></div>${[['soundToggle','sound'],['musicToggle','music'],['motionToggle','motion']].map(([id,key])=>`<div class="setting-row"><label for="${id}">${t(key)}</label><input type="checkbox" id="${id}" ${game.settings[key]?'checked':''}></div>`).join('')}<div class="setting-row"><label for="volume">${t('volume')}</label><input type="range" id="volume" min="0" max="100" value="${game.settings.volume*100}"></div><div class="setting-row"><label for="quality">${t('quality')}</label><select id="quality"><option value="high" ${game.settings.quality==='high'?'selected':''}>${t('high')}</option><option value="low" ${game.settings.quality==='low'?'selected':''}>${t('low')}</option></select></div><p class="fine-print">${t('accessibility')}</p><div class="settings-buttons"><button id="exportSave">${t('export')}</button><button id="importSave">${t('import')}</button><button id="restoreBackup">${t('restore')}</button><button id="fullscreen">${t('fullscreen')}</button></div><input id="saveFile" type="file" accept="application/json,.json" hidden><button id="cheatOptions">${t('cheats')}</button><button id="resetProgress" class="danger" ${!game.started?'disabled':''}>${t('reset')}</button><p class="fine-print">${t('optionsNote')}</p></div>`);
 $('languageSelect').onchange=e=>{changeLanguage(e.target.value);options();};
 for(const [id,key] of [['soundToggle','sound'],['musicToggle','music'],['motionToggle','motion']])$(id).onchange=()=>{game.settings[key]=$(id).checked;configure();sound.unlock();persist();};
 $('volume').oninput=()=>{game.settings.volume=Number($('volume').value)/100;sound.configure(game.settings,game.active);persist();};$('quality').onchange=()=>{game.settings.quality=$('quality').value;configure();persist();};
 $('exportSave').onclick=exportSave;$('importSave').onclick=()=>$('saveFile').click();$('saveFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error();replaceDialog(E.cleanGame(JSON.parse(await file.text())),t('importTitle'));}catch{toast(t('importFail'));}};
 $('restoreBackup').disabled=!S.read(S.backup);$('restoreBackup').onclick=()=>{try{replaceDialog(E.cleanGame(JSON.parse(S.read(S.backup))),t('restoreTitle'));}catch{toast(t('restoreFail'));}};
 $('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast(t('fullscreenFail'));}};
 $('resetProgress').onclick=()=>{open(t('resetTitle',{world:b(game.active).name}),`<p>${t('resetDesc')}</p><button class="danger wide" id="confirmReset">${t('reset')}</button>`);$('confirmReset').onclick=()=>{persist(true);game.archive[game.active]=[...new Set([...game.archive[game.active],...s.discovered])];s=game.worlds[game.active]=E.fresh();busy=0;select(null);scene.enter(game.active);close();update();updateHome();persist();};};
 $('cheatOptions').onclick=()=>{open(t('cheats'),`<p>${t('cheatIntro')}</p><label for="cheatInput">${t('cheatCode')}</label><div class="cheat-entry"><input id="cheatInput" type="text" autocomplete="off" maxlength="12" autocapitalize="characters" spellcheck="false"><button id="submitCheat" class="primary">${t('activate')}</button></div><ul class="instructions">${['cheatMoney','cheatWorld','cheatEvolve','cheatPulse'].map(key=>`<li>${t(key)}</li>`).join('')}</ul>`);const submit=()=>{const code=$('cheatInput').value.trim().toUpperCase();if(runCheat(code))close();};$('submitCheat').onclick=submit;$('cheatInput').onkeydown=e=>{if(e.key==='Enter')submit();};};
}
$('settings').onclick=options;$('homeOptions').onclick=options;
function about(){open(t('aboutTitle'),`<p class="story">Amoeba Evolution</p><p>${t('aboutText')}</p><p class="fine-print">${t('aboutVersion')}</p><p class="fine-print">${t('fiction')}</p>`);}
$('credits').onclick=about;$('homeCredits').onclick=about;
let padState=[],padClock=0;
function gamepad(dt){padClock+=dt;if(padClock<.1)return;padClock=0;const pad=navigator.getGamepads?.()?.find?.(p=>p);if(!pad)return;const current=pad.buttons.map(v=>v.pressed),press=i=>current[i]&&!padState[i];if(modal.open||home){const scope=modal.open?modal:$('homeScreen'),buttons=[...scope.querySelectorAll('button:not(:disabled),select,input')].filter(el=>el.offsetParent!==null);let i=buttons.indexOf(document.activeElement);if(press(13)||press(15))buttons[(i+1)%buttons.length]?.focus();if(press(12)||press(14))buttons[(i-1+buttons.length)%buttons.length]?.focus();if(press(0)&&document.activeElement.tagName==='BUTTON')document.activeElement.click();if(press(1)&&modal.open)close();}else{if(press(9)&&!otherTab)togglePause();if(!blocked()){if(press(15)||press(13))selectNext(1);if(press(14)||press(12))selectNext(-1);if(press(0))mergeSelected();if(press(2))buy();if(press(3))pulse();}}padState=current;}
function frame(time){const dt=last?Math.min(.1,(time-last)/1000):0;last=time;const isPaused=paused();sound.pause(isPaused);gamepad(dt);
 if(home){if(!document.hidden)homeArt.draw(dt);}else{
  if(!isPaused){busy=Math.max(0,busy-dt);const born=E.tick(s,dt,game.active,game.cycles);if(born){scene.birth(born);update();}scene.update(dt,s.creatures,drag?.c);saveClock+=dt;if(saveClock>=5){persist();saveClock=0;}if(pendingEnding&&busy===0){pendingEnding=false;ending();}}
  scene.draw(s.creatures,isPaused?0:dt);
 }
 uiClock+=dt;if(uiClock>=.15){if(!home)refreshNumbers();uiClock=0;}if(toastClock>0){toastClock-=dt;if(toastClock<=0)$('toast').classList.remove('visible');}requestAnimationFrame(frame);
}
window.addEventListener('storage',e=>{if(e.key===ownerKey&&e.newValue!==String(sessionId)){otherTab=true;clearDrag();sound.pause(true);toast(t('otherTab'));refreshNumbers();}});
document.addEventListener('visibilitychange',()=>{last=0;clearDrag();if(document.hidden){hiddenAt=Date.now();if(game.started)persist();sound.pause(true);}else{if(!otherTab&&hiddenAt&&game.started&&!home&&!manualPause&&!modal.open){const reward=E.offline(game);if(reward)toast(t('offline',{n:number(reward)}));persist();}hiddenAt=0;sound.pause(paused());update();}});
window.addEventListener('amoeba-back',()=>{if(modal.open)close();else if(home){persist();window.AmoebaNative?.exit();}else if(manualPause)goHome();else togglePause();});
window.addEventListener('pagehide',()=>{if(game.started)persist();});
configure();scene.enter(game.active);update();updateHome();requestAnimationFrame(frame);
if(loaded.recovered)toast(t('recovered'));
if('serviceWorker'in navigator&&location.protocol!=='file:'&&!['127.0.0.1','localhost'].includes(location.hostname)&&!window.AmoebaNative)navigator.serviceWorker.register('sw.js').catch(()=>{});
})();



